<table align="left">
    <tr>
        <th><h1>CS 3368</h1><h2>Introduction to Artificial Intelligence</h2>
        <h1 style="color:maroon;">Team Project Assignment</h1>
        <h2 style="color:maroon;">Third Submission</h2></th>
        <th><img src="https://www.ttu.edu/traditions/images/raiderstatue.jpg" width=225 height=116 /></th>
        <th><p>Texas Tech University Matador Song</p>
            <p>Fight, Matadors, for Tech!<br>
                Songs of love we'll sing to thee,<br>
                Bear our banners far and wide.<br>
                Ever to be our pride,<br>
                Fearless champions ever be.<br>
                Stand on heights of victory.<br>
                Strive for honor evermore.<br>
                Long live the Matadors!</p>
                <p>Music by Harry Lemaire, words by R.C. Marshall</p></th>
    </tr>
</table>

<hr>
<h1 style="color:darkgoldenrod">Team 12: Blue2</h1>

<ul>
<li style="color:maroon"><h4><bf>Harper Hill</bf></h4></li>
<li style="color:maroon"><h4><bf>Kharis Asifor-Paul</bf></h4></li>
<li style="color:maroon"><h4><bf>Zack Sims</bf></h4></li>
</ul>

<hr>
<h1 style="color:darkgoldenrod">AI Problem</h1>

<ul>
<li style="color:maroon"><h4><bf>What is the problem on which the team worked for this submission?</bf></h4></li>
    <ul>
        <li>Malicous Software infection computers</li>
        <li>Lackluster malware detection in modern security software</li>
    </ul>
<li style="color:maroon"><h4><bf>Is it the same or a different problem than the problem(s) proposed in the proposal or the second submission?  If changes in scope or other changes to the problem have been made since the proposal or second submission, please explain here.</bf></h4></li>
    <ul>
        <li>Same problem proposed in the proposal and our second submission</li>
    </ul>
<li style="color:maroon"><h4><bf>Please summarize here what advances and lessons learned the team made in solving the problem for this submission.</bf></h4></li>
    <ul>
        <li><h5>Advances:</h5>
            <ul>
                <li>The CNN model achieved a Test Accuracy of 93% when trained on the BODMAS feature vectors.</li>
                <li>The data required for the decision tree has been filtered to remove unnecessary information.</li>
            </ul>
        </li>
        <li><h5>Lessons Learned:</h5>
            <ul>
                <li>Benchmarking against journal papers helps identify weaknesses in preprocessing and training, and hybrid models combining CNNs and RNNs require careful integration but can potentially improve sequential data processing.</li>
                <li>The quality and diversity of features in the BODMAS dataset significantly impact the accuracy and generalizability of the model.</li>
                <li>The training/testing split for a dataset can affect the reported accuracy of a model.</li>
            </ul>
        </li>
    </ul>
</ul>

<hr>
<h1 style="color:darkgoldenrod">What other ideas, models, approaches, and/or helpful suggestions have you found since the last team submission related to solving the AI problem or similar problems by others?</h1>

<hr>
<h2 style="color: teal">From Journal/Conference Papers</h2>

<p>Papers from previous submissions should not be listed here.</p>

<p>Journal and conference papers report on research to solve problems.  They do not necessarily have tutorial instructions, but they do report on many ideas that were used in the past, the ideas used by the authors to solve the problem in the paper, and ideas for future research.  They can help you narrow down quickly promising ideas to use to solve a problem.  Examples of ideas are using A-star search and developing a modified version of A-star search to reduce the state space by sampling the actions.  Normal data processing, such as cleaning data, or normal steps to solve a problem would not be the ideas for which you are searching as you read the paper.</p>
<p>Another thing that papers have are results that you can use to compare to your solution so you can see if your solution approach has merit.  If your solution does not do as well as solutions reported in the papers, use the papers to find ideas to improve the solution that you have.</p>
<p>You want to look for papers listed in the Scopus database available through the <a href="https://ttu-primo.hosted.exlibrisgroup.com/primo-explore/dbsearch?vid=01TTU">TTU Library's Website</a>, and enter "Scopus" into the search box.  Papers listed in Scopus will be in venues recognized by scholars and the papers you use should have at least 5 citations.  In particular, when reading the papers, look for relationships among the solution ideas, how the authors evaluated their solutions, and what promising ideas the authors think could improve their work.</p>

<p>Use <a href="https://ieee-dataport.org/sites/default/files/analysis/27/IEEE%20Citation%20Guidelines.pdf">IEEE</a> or <a href="https://www.acm.org/publications/authors/reference-formatting">ACM</a> format for listing the paper references.  An example is following.</p>
<hr>

<ul>
<li style="color:maroon"><h4><bf>Md. A. Hossain, T. Hasan, F. Ahmed, S. H. Cheragee, M. H. Kanchan, and M. A. Haque, "Towards superior android ransomware detection: An ensemble machine learning perspective," Cyber Security and Applications, vol. 3, p. 100076, 2025. [Online]. Available: https://doi.org/10.1016/j.csa.2024.100076.</bf></h4></li>
    <ul>
        <li><h5>Problem:</h5> Ransomware protection for Android devices is inadequate, leaving devices vulernable to attacks. </li>
        <li><h5>Past Solution Ideas:</h5>FNN using Keras Sequential, SVM, KNN, Gradient Boosting, AdaBoost.</li>
        <li><h5>Authors' Solution Ideas:</h5>XG Boost, Random Forest, CatBoost</li>
        <li><h5>Future Promising Solution Ideas:</h5>XGBoost's efficiency and scalability makes it well suited for large datasets, as well as supporting regularization to avoid overfitting. </li>
        <li><h5>Evaluation Ideas:</h5>Paired t-test and Confusion Matrix, as well as the standard accuracy, precision, recall and F1-Score.</li>
        <li><h5>Ideas the Team Would Like to Use From This Paper:</h5>Implement XGBoost, possibly use a confusion matrix for evaluation.</li>
    </ul>
<li style="color:maroon"><h4><bf>Romero, C. N., Mital, M. E. G., Rostata, Z. D., & Martinez, M. A. M. (2024). Investigating the impact of training and testing ratios on the performance of an AI-based malware detector using MATLAB. E3S Web of Conferences, 50, 001015. https://doi.org/10.1051/e3sconf/202450001015</bf></h4></li>
    <ul>
        <li><h5>Problem:</h5> Different AI models and tasks will respond different to different splits between training and testing data.</li>
        <li><h5>Past Solution Ideas: </h5> Many people use a "standard" 70/30 training/testing split, or any other split without assessing whether that's the most appropriate one for the task at hand.</li>
        <li><h5>Authors' Solution Ideas:</h5>Evaluating your model and determining which kind of training/testing split would be most appropriate.</li>
        <li><h5>Future Promising Solution Ideas:</h5>Using different training splits to better assess the capabilities of the model being tested.</li>
        <li><h5>Evaluation Ideas:</h5>Using different training/testing splits to assess models.</li>
        <li><h5>Ideas the Team Would Like to Use From This Paper:</h5>Test AI models using different training splits like 50/50, 70/30, and 80/20 to see if any of them work better with the model being implemented.</li>
    </ul>
<li style="color:maroon"><h4><bf>A. Bensaoud, J. Kalita, and M. Bensaoud, "A Survey of Malware Detection Using Deep Learning," Journal of Information and Security Advances, vol. 9, no. 2, pp. 45–59, Jul. 2024.</bf></h4></li>
    <ul>
        <li><h5>Problem: </h5>The paper highlights the challenges in detecting malware due to the evolving complexity of malware behavior, and limitations of traditional methods such as signature- and heuristic-based detection, which struggle with novel or polymorphic malware.</li>
        <li><h5>Past Solution Ideas: </h5>Examining the binary code without execution (e.g., entropy, API calls), earlier models relied on handcrafted features for malware classification.</li>
        <li><h5>Authors' Solution Ideas:</h5>The authors propose using DL techniques, such as CNNs for image-based malware detection and hybrid CNN-RNN models for sequential features. They emphasize the role of pre-trained models and Explainable AI to improve scalability and transparency.</li>
        <li><h5>Future Promising Solution Ideas:</h5>Exploring unsupervised learning for detecting unseen malware families and adversarial robustness to evade attacks. The paper also stresses the need for Explainable AI to make malware detection models more transparent.</li>
        <li><h5>Evaluation Ideas:</h5>The authors benchmark accuracy, precision, recall, and F1-scores of DL models against traditional methods. They also evaluate the models' resilience to adversarial examples for robustness.</li>
        <li><h5>Ideas the Team Would Like to Use From This Paper:</h5>The team will adopt image-based detection with CNNs and explore hybrid CNN-RNN models to improve detection. Investigating adversarial robustness and integrating Explainable AI will also guide model development.</li>
    </ul>
</ul>

<hr>
<h2 style="color: teal">From Other Informal Resources</h2>
<hr>

<p>Informal resources from previous submissions should not be listed here.</p>

<p>Other informal resources include work that is not published in journals or conferences, such as blog sites, tutorials, posted software, software package websites, generative AI tools, and past class project reports that are available online.  Such resources may have concrete examples of how to do various solutions and have software packages or resources that can be used in the team's solution.  Such information and resources should be used to enable the team to go further and faster than they could have gone if the team had started from scratch.</p>
<hr>
<ul>
<li style="color:maroon"><h4><bf>GeeksforGeeks, "ML | Gradient Boosting," GeeksforGeeks, Accessed: Nov. 25, 2024, [Online]. Available: https://www.geeksforgeeks.org/ml-gradient-boosting/</bf></h4></li>
    <ul>
        <li><h5>Helpful information/code/ideas/examples:</h5>Using Gradient Boosting to minimize our loss function</li>
        <li><h5>What the team would like to use from this resource:</h5>Familiarizing ourselves with the sklearn libraries, as well as how we can effectively implement these techniques with our dataset</li>
    </ul>
<li style="color:maroon"><h4><bf>TutorialsPoint, "Scikit-learn - Boosting Methods," TutorialsPoint, Accessed: Nov. 25, 2024, [Online]. Available: https://www.tutorialspoint.com/scikit_learn/scikit_learn_boosting_methods.htm</bf></h4></li>
    <ul>
        <li><h5>Helpful information/code/ideas/examples:</h5>Comparing Gradient Boosting vs Ada Boosting, how to use both on datasets</li>
        <li><h5>What the team would like to use from this resource:</h5>Further our knowledge and experience with boosting and AI/ML techniques</li>
    </ul>
<li style="color:maroon"><h4><bf>Y. Young, "BODMAS: An Open Dataset for Malware Analysis," WhyIsYoung Blog, 2021. Available: https://github.com/whyisyoung/BODMAS?tab=readme-ov-file</bf></h4></li>
    <ul>
        <li><h5>Helpful information/code/ideas/examples:</h5>Includes feature vectors for over 57,000 malware samples and 77,000 benign samples across 581 malware families, and provides curated metadata for static analysis, including byte histograms, entropy, and more.</li>
        <li><h5>What the team would like to use from this resource:</h5>Preprocessed feature vectors for training machine learning models, comprehensive labeling of malware families to evaluate classification performance, and feature diversity to enhance model robustness and generalizability.</li>
    </ul>
</ul>

<hr>
<h1 style="color: darkgoldenrod">Past Plans and Actual Tasks for the Third Project Assignment Submission</h1>

<p>The third project assignment submission is the final status report on how far the team has gotten in solving the problem.  Overall, status reports will include but not be limited to items, such as updates to the problem scope, lessons learned, finding more ideas in the conference and journal paper literature as well as informal resources, data sources found, current solution status and performance, comparison of solution to past approaches, software developed and packages used, hardware used, testing, and consideration of new solution approaches.</p>

<p>Each team member should catalog the actual work tasks performed for this submission including specfic papers and resources found, AI solution models proposed, preliminary investigative work on a software prototype, researching evaluation strategies for the team's solution, finding needed data files, interviewing experts, solving subproblems, planning, designing, coding, testing, and anything related to helping the team complete the submission well.</p>

<p>Tasks should have enough detail to understand clearly and specifically what was done.  For example, rather than say, "found and wrote up 2 conference papers", include the authors, such as "found and wrote up 2 conference papers by Smith et al, 2022, and Breugrand et al, 2019" so it is clear which papers were contributed to a submission.</p>

<hr>

Each team member plans to apply an AI solution to the problem and has the following accomplishments and plans:
<table>
    <tr>
        <th style="color: maroon"><bf>Team Member Name</bf></th>
        <th style="color: maroon"><bf>Planned Team Member Tasks for Third Submission</bf></th>
        <th style="color: maroon"><bf>Actual Team Member Tasks for Third Submission</bf></th>
    </tr>
    <tr style="text-align:left">
        <th>Harper Hill</th>
        <th><ul>
            <li><bf>Tasks planned from the proposal submission</bf></li>
            <ul>
                <li>Refine final models ~5-6 hours</li>
                <li>Establish testing methodology, ~2-3 hours</li>
            </ul>
            <br>
            <li><bf>Tasks planned from the second submission</bf></li>
            <ul>
                <li>Optimize Decision Tree. -4 hours</li>
                <li>Implement and test KNN. -10 hours</li>
                <li>Test performance and compare to performance of existing models. -5 hours</li>
                <li>Fill out report. -3 hours</li>
            </ul>
            </ul>
        </th>
        <th><ul>
            <li><bf>Tasks actually done for the third submission</bf></li>
            <ul>
                <li>Optimize Decision Tree. -5 hours</li>
                <li>Test performance and compare to performance of existing models. -4 hours</li>
                <li>Fill out report. -3 hours</li>
            </ul>
            <br>
            </ul>
        </th>
    </tr>
    <tr style="text-align:left">
        <th>Kharis Asifor-Paul</th>
        <th><ul>
            <li><bf>Tasks planned from the proposal submission</bf></li>
            <ul>
                <li>Investigate AI-based malware detection techniques and gather relevant datasets (malicious vs. benign software), ~5hrs</li>
                <li>Design AI models, like decision trees or neural networks, that classify software based on the patterns in the collected data, ~4-5hrs</li>
            </ul>
            <br>
            <li><bf>Tasks planned from the second submission</bf></li>
            <ul>
                <li>Complete model training; achieve preliminary results of at least 85% accuracy, ~5-6hrs</li>
                <li>Documented issues with dataset imbalance and strategies to address this through resampling, ~2-3hrs</li>
                <li>Finalize findings and conclude report, ~2hrs</li>
            </ul>
            </ul>
        </th>
        <th><ul>
            <li><bf>Tasks actually done for the third submission</bf></li>
            <ul>
                <li>Integrated the BODMAS dataset into the workflow and applied normalization techniques using MinMaxScaler to prepare features for the CNN model, ~5-6hrs</li>
                <li>Designed and trained a Convolutional Neural Network (CNN) for malware classification and achieved a test accuracy of 93%, validating the effectiveness of the feature selection and preprocessing, ~7-8hrs</li>
                <li>Conducted performance evaluation and comparison and benchmarked the CNN model against similar models from the informal resource, ~5hrs</li>
            </ul>
            <br>
            </ul>
        </th>
    </tr>
    <tr style="text-align:left">
        <th>Zack Sims</th>
        <th><ul>
            <li><bf>Tasks planned from the proposal submission</bf></li>
            <ul>
                <li>Implement AI search and other useful AI techniques into problem, ~4-5 hours</li>
                <li>Develop code base and develop agent, ~4-5 hours</li>
            </ul>
            <br>
            <li><bf>Tasks planned from the second submission</bf></li>
            <ul>
                <li>Implement the agent in software, 10+ hours</li>
                <li>Choose a dataset to train our agent on, 1-2 hours of deliberation</li>
                <li>Continue work in developing algorithms and software to aid our agent in making optimal choices, 10-12 hours</li>
                <li>Perform performance benchmarking and compare these results with other implemenations, 6 hours</li>
            </ul>
            </ul>
        </th>
        <th><ul>
            <li><bf>Tasks actually done for the third submission</bf></li>
            <ul>
                <li>task, actual time or time estimate</li>
                <li>task, actual time or time estimate</li>
            </ul>
            <br>
            </ul>
        </th>
    </tr>
</table>

<hr>
<h1 style="color: darkgoldenrod">Current Solution Status</h1>
<hr>

<h2 style="color:teal">What computer hardware, programming language, main software packages, and data files are recommended to be used to run the software for this submission?</h2>
    <ul>
        <li><h5 style="color:maroon">Computer Hardware</h5>Minimum: Any modern, multi-core CPU, 4GB RAM minimum. Reccomended: 8 core CPU, 8-16 GB memory. </li>
        <li><h5 style="color:maroon">Programming Language</h5>Python 3.12.2</li>
        <li><h5 style="color:maroon">Main Software Packages</h5>scikit-learn, pandas, numpy, matplotlib</li>
        <li><h5 style="color:maroon">Data</h5>Malware database for training from: 
            <li>https://www.kaggle.com/datasets/subhajournal/android-malware-detection
    <li> https://github.com/whyisyoung/BODMAS?tab=readme-ov-file</li>
    </ul>
</ul>

<hr>
<h2 style="color: teal">What is the performance of the team's solutions in comparison with results from journal/conference papers and other informal resources since the last submission?</h2>

<p>Comparisons from previous submissions should not be listed here.</p>

<p>For the third submission, each team member should plan to add at least one more reference for comparison of performance regardless of how many are given in submission two.  Performance includes but is not limited to the amount of memory consumed, the order of the algorithms used, computation time, number of operations performed, experimental results on various data sets or trials, and measurements, such as precision, recall, accuracy, F-measure, and cluster purity/silouette.  Graphs, such as the ROC curve, precision/recall curve, scatter plots showing the relationship between two attributes, line charts showing model performance at various training points, and bar charts comparing approaches, may also be used.</p>

<p>If a direct comparison is not available, try to find a reference that is similar in nature.  In addition, discuss with the course instructors any difficulty you are having in finding references to compare against.  Other ideas include implementing more solutions to compare against each other.</p>

<hr>

<h3 style="color:maroon">Harper Hill - Cleaning Dataset, Narrowing to Most Important Attributes, and Expirementing With Different Training/Testing Splits</h3>

<p>For this sprint I focused on testing the effects of manipulating the dataset and the training/testing split on the accuracy of the Decision Tree model.  I wanted to see how much of an effect there was on the model after I removed unnecessary columns from the dataset, after I selected k best features, and changed the percentage of data used for testing and training.</p>

<h4 style="color:darkblue">Paper/Informal Reference:</h4>
<p>Romero, C. N., Mital, M. E. G., Rostata, Z. D., & Martinez, M. A. M. (2024). Investigating the impact of training and testing ratios on the performance of an AI-based malware detector using MATLAB. E3S Web of Conferences, 50, 001015. https://doi.org/10.1051/e3sconf/202450001015</p>

<table>
    <tr>
        <th style="color: darkgreen"><bf>Comparison with Reference Solution</bf></th>
        <th style="color: darkgreen"><bf>Reasons why the performance of the team's solution is better/same/worse</bf></th>
    </tr>
    <tr>
        <th>The reference solution demonstrated an accuracy of 52.20% with a 50/50 training/testing split, and a 49.33% accuracy with a 70/30 split.  Our implementation had a 50.01% accuracy with a 50/50 split and a 50.03% accuracy with a 70/30 split.  Our accuracy peaked at a 50.05% with a 68/32 training split.</th>
        <th>When testing our model I found that removing unnecessary data from the dataset didn't affect the outcome of the model, and that selecting k best features only lowered the accuracy of the model below k=45, and didn't change it above that.  I think this shows that decision trees are fairly robust since ours wasn't being tricked by the unimportant data it was given, and it can make use of a wide range of factors to help it make it's decisions.  The accuracy peaking at a 68/32 split I thought was interesting since it dropped off on either side of that.  This could possibly be due to how the data is distributed in the table and the difference is very small, but it's good to know that this is something that can affect the evaluation of our model.</th>
    </tr>
</table>

...

<hr>

<h3 style="color:maroon">Kharis Asifor-Paul - Integration of Advanced Static Analysis Features</h3>

<p>The team's solution utilizes a Convolutional Neural Network (CNN) trained on static analysis features derived from the BODMAS dataset. These features include byte histograms and entropy values, which are normalized and fed into the CNN for binary classification of malware and benign files. The model achieved a validation accuracy, demonstrating its capability to detect malware effectively. Future iterations aim to incorporate Explainable AI concepts and hybrid CNN-RNN architectures to improve interpretability and robustness.</p>

<h4 style="color:darkblue">Paper/Informal Reference:</h4>
<p>Y. Young, "BODMAS: An Open Dataset for Malware Analysis," WhyIsYoung Blog, 2021. Available: https://github.com/whyisyoung/BODMAS?tab=readme-ov-file</p>

<table>
    <tr>
        <th style="color: darkgreen"><bf>Comparison with Reference Solution</bf></th>
        <th style="color: darkgreen"><bf>Reasons why the performance of the team's solution is better/same/worse</bf></th>
    </tr>
    <tr>
        <th>The CNN model achieved a Test Accuracy of 93% when trained on the BODMAS feature vectors.</th>
        <th>The CNN model outperformed traditional machine learning models (e.g., Decision Trees, which achieved ~85% accuracy on the same dataset). Feature normalization and early stopping techniques were crucial for preventing overfitting.</th>
    </tr>
</table>

...

<hr>

<h3 style="color:maroon">Zack Sims - Fill in Descriptive Name</h3>

<p>Fill in description of team solution</p>

<h4 style="color:darkblue">Paper/Informal Reference:</h4>
<p>Fill in reference journal</p>

<table>
    <tr>
        <th style="color: darkgreen"><bf>Comparison with Reference Solution</bf></th>
        <th style="color: darkgreen"><bf>Reasons why the performance of the team's solution is better/same/worse</bf></th>
    </tr>
    <tr>
        <th>Fill in reference description solution and performance, and comparison between team's solution and the reference's solution</th>
        <th>Fill in reasons for the performance differences or lack of differences between the reference and team solutions</th>
    </tr>
</table>

...

<hr>

<h3 style="color:maroon">Discussion/Summary of Solution Results</h3>

<p>Please use this section to use items, such as well-labeled graphs and tables, to show a comparison of all team member solutions against each other and with the paper/informal reference solutions, to show a summary of all solution results, and give a discussion of what could be planned to be done for a hypothetical next submission to continue to improve the performance of each team member's solution.</p>

<hr>



<h1 style="color: darkgoldenrod">Software</h1>
<hr>

<p>Please be sure to submit a requirements.txt file so that the instructors can easily run the code in this Jupyter Notebook.  The requirements.txt file should be in the same working directory as the Jupyter Notebook.  Also, please give any special instructions beyond the normal running of code in a Jupyter Notebook, such as where data files should be placed if not in the working directory of this Jupyter Notebook or if some of the installed software packages have additional requirements beyond "pip install".</p>

<p>Each code cell should have contextually related code, such as a class, function implementing a major algorithm, or a set of short functions that support a larger function in a subsequent cell.  Code cells should also be present to show the performance/evaluation of a solution through well labeled graphs, tables, and/or performance measure values.</p>

<p>The code cells also can be organized by each team member's solution.</p>

<p>Each major set of related code cells should have the purpose of the code cells, the paper/informal references used (if any) to develop the code in the code cells, the team members who worked on the code cells, and major changes made to the code in the code cells by team members for this submission.  Changes made in a previous submission should not be included.</p>

<hr>

<h2 style="color: teal">Are there any special instructions for running the code in this Jupyter Notebook for this submission?</h2>

<ul>
    <li>Download 'bodmas_metadata.csv' dataset from GitHub repo, available at https://github.com/whyisyoung/BODMAS?tab=readme-ov-file</li>
    <li>To get the dataset for the Decision Tree solution, download Android_Malware.csv from this link https://www.kaggle.com/datasets/subhajournal/android-malware-detection</li>
</ul>

<hr>

In [47]:
#to capture all of the installed packages so far (run by the team to submit with the Jupyter notebook)
%pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.


In [48]:
#packages to import to run the code in the Jupyter Notebook
#For Decision Tree implementation
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import tree
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_selection import VarianceThreshold

<h3 style="color:maroon">Code Cell Block - Data Preparation for Decision Tree</h3>

<h4 style="color:darkgreen">Purpose</h4>

<p>The below code imports the dataset, removes unecessary columns, and displays some information about it for the user.</p>

<h4 style="color:darkgreen">References used to develop the code</h4>

<ul>
    <li>https://www.kaggle.com/code/mahmoudasla/android-malware-detection-0c4368</li>
</ul>

<h4 style="color:darkgreen">Team members contributing to the code cell block</h4>

<h5 style="color:darkblue">Harper Hill</h5>
<li>This code block is reused from the second submission for convenience and consistency</li>
<ul>
    <li>11/03/2024 - Added dataset and some cleaning of data</li>
</ul>

In [49]:
df=pd.read_csv('Dataset/Android_Malware.csv', low_memory=False)
df.shape
df.head()
df.columns

df.drop(['Unnamed: 0','Flow ID',' Timestamp',' CWE Flag Count',' Down/Up Ratio','Fwd Avg Bytes/Bulk'], axis=1, inplace=True)
le = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object':
        df[i] = le.fit_transform(df[i])
df.drop_duplicates(inplace=True)
df.isnull().sum().sort_values(ascending=False).head()
df.dropna(axis=0,inplace=True)


ParserError: Error tokenizing data. C error: out of memory

<h3 style="color:maroon">Comparing Boosted Decision Trees no Non-Boosted Trees</h3>

<h4 style="color:darkgreen">Purpose:</h4>

<p>See what impact boosting will have on our current decison tree</p>

<h4 style="color:darkgreen">References used to develop the code</h4>

<ul>
    <li>GeeksforGeeks, "ML | Gradient Boosting," GeeksforGeeks, Accessed: Nov. 25, 2024, [Online]. Available: https://www.geeksforgeeks.org/ml-gradient-boosting/</li>
</ul>

<h4 style="color:darkgreen">Team members contributing to the code cell block</h4>

<h5 style="color:darkblue">Zack Sims</h5>

<ul>
    <li>11/23/2024: Wrote software and compared results</li>
</ul>

In [ ]:
#this is our non boosted decision tree implementation from the previous stage, not unique to this submission
X = df.values[:, 0:78]
Y = df.values[:, 79]

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=.3, random_state=100)

#entropy clf
clf_entropy = DecisionTreeClassifier(criterion="entropy", random_state=100, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(x_train, y_train)

#gini clf
clf_gini = DecisionTreeClassifier(criterion="gini",random_state=100,max_depth=3,min_samples_leaf=5)
clf_gini.fit(x_train, y_train)

#Make prediction for entropy tree
entropy_y_pred = clf_entropy.predict(x_test)
print("Predicted values:")
print(entropy_y_pred)

#Print confusion matrix and accuracy for entropy tree
print("Confusion Matrix: ", confusion_matrix(y_test, entropy_y_pred))
print("Accuracy : ", accuracy_score(y_test, entropy_y_pred)*100)
print("Report : ", classification_report(y_test, entropy_y_pred))

#commented out graphics for screen space and conveinience
#plt.figure(figsize=(15,10))
#plot_tree(clf_entropy, feature_names=df.columns, class_names=['Android_Adware', 'Android_Scareware', 'Android_SMS_Malware', 'Benign'], filled=True, rounded=True)
#plt.show()

#Make prediction for gini tree
gini_y_pred = clf_gini.predict(x_test)
print("Predicted values:")
print(gini_y_pred)

#Print confusion matrix and accuracy for gini tree
print("Confusion Matrix: ", confusion_matrix(y_test, gini_y_pred))
print("Accuracy : ", accuracy_score(y_test, gini_y_pred)*100)
print("Report : ", classification_report(y_test, gini_y_pred))

#plt.figure(figsize=(15,10))
#plot_tree(clf_gini, feature_names=df.columns, class_names=['Android_Adware', 'Android_Scareware', 'Android_SMS_Malware', 'Benign'], filled=True, rounded=True)
#plt.show()


Predicted values:
[2. 2. 0. ... 0. 0. 2.]
Confusion Matrix:  [[33061   207 11042     0]
 [ 8988  5160  4997     0]
 [19163  1194 14528     0]
 [ 4344    57  2703     0]]
Accuracy :  50.02560600887676
Report :                precision    recall  f1-score   support

         0.0       0.50      0.75      0.60     44310
         1.0       0.78      0.27      0.40     19145
         2.0       0.44      0.42      0.43     34885
         3.0       0.00      0.00      0.00      7104

    accuracy                           0.50    105444
   macro avg       0.43      0.36      0.36    105444
weighted avg       0.50      0.50      0.47    105444

Predicted values:
[2. 2. 0. ... 0. 0. 2.]
Confusion Matrix:  [[33061   207 11042     0]
 [ 8988  5160  4997     0]
 [19163  1194 14528     0]
 [ 4344    57  2703     0]]
Accuracy :  50.02560600887676
Report :                precision    recall  f1-score   support

         0.0       0.50      0.75      0.60     44310
         1.0       0.78      0.27   

c:\Users\Zack\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Zack\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Zack\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

In [ ]:
#this will be the gradient boosting implementation
X = df.values[:, 0:78]
Y = df.values[:, 79]

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = .3, random_state=100)

#classify and fit to the training set
gb_clf = GradientBoostingClassifier(n_estimators = 100, learning_rate = .05, random_state = 100, max_features = 5)
gb_clf.fit(x_train, y_train)

gb_prediction = gb_clf.predict(x_test)
print("Predicted values:\n", gb_prediction)

#print actual values
print("Confusion Matrix: ", confusion_matrix(y_test, gb_prediction))
print("Accuracy : ", accuracy_score(y_test, gb_prediction)*100)
print("Report : ", classification_report(y_test, gb_prediction))


Predicted values:
 [1.20858525 1.29126211 1.03523184 ... 1.00345389 0.99009336 1.05952189]


ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

<h3 style="color:maroon">Comparing Decision Trees to Decision Trees With Refined Datasets</h3>

<h4 style="color:darkgreen">Purpose:</h4>

<p>See what impact removing unnecessary data will have on the accuracy of the decision tree.  Also testing what effect changing the testing/training split will have on the accuracy of the model.</p>

<h4 style="color:darkgreen">References used to develop the code</h4>

<ul>
    <li>Athira, D. Baburaj and D. Gupta, "A Comprehensive Exploration of Machine Learning and Explainable AI Techniques for Malware Classification," 2024 2nd World Conference on Communication & Computing (WCONF), RAIPUR, India, 2024, pp. 1-7, doi: 10.1109/WCONF61366.2024.10692299. keywords: {Measurement;Deep learning;Recurrent neural networks;Explainable AI;Forestry;Boosting;Malware;Convolutional neural networks;Computer crime;Random forests;Malware;Machine Learning;KNN;Random Forest;Decision Tree;XGBoost;AdaBoost},</li>
</ul>

<h4 style="color:darkgreen">Team members contributing to the code cell block</h4>

<h5 style="color:darkblue">Harper Hill</h5>

<ul>
    <li>11/24/2024: Added Variance Threshold and SelectKBest to optimize data being fed to decision tree.</li>
</ul>

In [50]:
#this is our non boosted decision tree implementation from the previous stage
#with the addition of removing features that have no variance
#and selecting k best features
#as well as changing the training/testing split

X_old = df.values[:, 0:78]
Y = df.values[:, 79]

vt = VarianceThreshold(threshold=0.0)
X_no_variance = vt.fit_transform(X_old)

selector = SelectKBest(score_func=f_classif, k=45)
X = selector.fit_transform(X_no_variance,Y)

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=.32, random_state=100)

#entropy clf
clf_entropy = DecisionTreeClassifier(criterion="entropy", random_state=100, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(x_train, y_train)

#gini clf
clf_gini = DecisionTreeClassifier(criterion="gini",random_state=100,max_depth=3,min_samples_leaf=5)
clf_gini.fit(x_train, y_train)

#Make prediction for entropy tree
entropy_y_pred = clf_entropy.predict(x_test)
print("Entropy Tree")
print("Predicted values:")
print(entropy_y_pred)

#Print confusion matrix and accuracy for entropy tree
print("Confusion Matrix: ", confusion_matrix(y_test, entropy_y_pred))
print("Accuracy : ", accuracy_score(y_test, entropy_y_pred)*100)
print("Report : ", classification_report(y_test, entropy_y_pred))

#commented out graphics for screen space and conveinience
#plt.figure(figsize=(15,10))
#plot_tree(clf_entropy, feature_names=df.columns, class_names=['Android_Adware', 'Android_Scareware', 'Android_SMS_Malware', 'Benign'], filled=True, rounded=True)
#plt.show()

#Make prediction for gini tree
gini_y_pred = clf_gini.predict(x_test)
print("Gini tree")
print("Predicted values:")
print(gini_y_pred)

#Print confusion matrix and accuracy for gini tree
print("Confusion Matrix: ", confusion_matrix(y_test, gini_y_pred))
print("Accuracy : ", accuracy_score(y_test, gini_y_pred)*100)
print("Report : ", classification_report(y_test, gini_y_pred))

#plt.figure(figsize=(15,10))
#plot_tree(clf_gini, feature_names=df.columns, class_names=['Android_Adware', 'Android_Scareware', 'Android_SMS_Malware', 'Benign'], filled=True, rounded=True)
#plt.show()


Entropy Tree
Predicted values:
[2. 2. 0. ... 0. 0. 0.]
Confusion Matrix:  [[35265   222 11752     0]
 [ 9571  5485  5350     0]
 [20442  1270 15544     0]
 [ 4633    59  2881     0]]
Accuracy :  50.050678379003145


C:\Users\harpe\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\harpe\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\harpe\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Report :                precision    recall  f1-score   support

         0.0       0.50      0.75      0.60     47239
         1.0       0.78      0.27      0.40     20406
         2.0       0.44      0.42      0.43     37256
         3.0       0.00      0.00      0.00      7573

    accuracy                           0.50    112474
   macro avg       0.43      0.36      0.36    112474
weighted avg       0.50      0.50      0.47    112474

Gini tree
Predicted values:
[2. 2. 0. ... 0. 0. 0.]
Confusion Matrix:  [[35265   222 11752     0]
 [ 9571  5485  5350     0]
 [20442  1270 15544     0]
 [ 4633    59  2881     0]]
Accuracy :  50.050678379003145
Report :                precision    recall  f1-score   support

         0.0       0.50      0.75      0.60     47239
         1.0       0.78      0.27      0.40     20406
         2.0       0.44      0.42      0.43     37256
         3.0       0.00      0.00      0.00      7573

    accuracy                           0.50    112474
   macro

C:\Users\harpe\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\harpe\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\harpe\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


<h3 style="color:maroon">Integration of BODMAS Dataset with CNN for Malware Classification</h3>

<h4 style="color:darkgreen">Purpose</h4>

<p>Train a Convolutional Neural Network (CNN) for binary classification of malware and benign files. This demonstrates the integration of advanced static analysis features into a deep learning model for malware detection.</p>

<h4 style="color:darkgreen">References used to develop the code</h4>

<ul>
    <li>https://github.com/whyisyoung/BODMAS?tab=readme-ov-file.</li>
</ul>

<h4 style="color:darkgreen">Team members contributing to the code cell block</h4>

<h5 style="color:darkblue">Kharis Asifor-Paul</h5>

<ul>
    <li>11/23/2024 - Integrated the BODMAS dataset into the project, trained a CNN model, and benchmarked results.
</li>
 

In [ ]:
# Import required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

In [ ]:
# Load the BODMAS feature vectors
filename = 'bodmas_metadata.csv'
data = pd.read_csv(filename)

# Explore the dataset structure
print(data.info())
print(data.head())

# Separate features and labels
X = data.drop('label', axis=1)  # Drop the label column to get features
y = data['label']  # Binary labels: 0 = benign, 1 = malware

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
# Define the CNN model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Early stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train the model
history = model.fit(
    X_train, y_train,
    epochs=15,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

In [ ]:
# Plot training and validation accuracy
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training vs. Validation Accuracy')
plt.show()